=== AgudemuBorjigin/SNAPlabonline/SNAPlabonline/tasks/media/schema/taskschema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Task schema",
    "description": "This schema attempts to validate if the basic task JSONs uploaded by experimenters",
    "type": "object",
    "properties":
        {
        "instructions": {"type": "array", "items": {"type": "string"}},
        "feedback": {"type": "boolean"},
        "serveraudio": {"type": "boolean"},
        "trials": 
            {
            "type": "array", 
            "items":
                {
                "type": "object",
                "properties":
                    {
                    "prompt": {"type": "string"},
                    "choices":
                        {
                        "type": "array",
                        "items":
                            {
                            "type": "string",
                            "minItems": 1,
                            "uniqueItems": true
                            }
                        },
                    "stimulus": {"type": "string", "pattern": "(wav)$"},
                    "answer": {"type": "integer", "minimum": 1}
                    }
                },
            "minItems": 1
            }
        },
    "required": ["instructions", "feedback", "serveraudio", "trials"],
    "additionalProperties": false
}

=== AgudemuBorjigin/SNAPlabonline/SNAPlabonline/tasks/media/json/exampleTask_jm09wFn.json
{
	"instructions": ["Wear Headphones", "Do Task"],
	"feedback": true,
	"serveraudio": true,
	"trials":[
		{
		"prompt": "Select one of the three options",
		"choices": ["FIRST", "SECOND", "THIRD"],
		"stimulus": "url1.wav",
		"answer": 1
		},
		{
		"prompt": "Select one of the four options",
		"choices": ["FIRST", "SECOND", "THIRD", "FOURTH"],
		"stimulus": "url2.wav",
		"answer": 2
		},
		{
		"prompt": "Select one of the six options",
		"choices": ["FIRST", "SECOND", "THIRD", "FOURTH",
			"FIFTH", "SIXTH"],
		"stimulus": "url3.wav",
		"answer": 3
		}
	]
}

=== AgudemuBorjigin/SNAPlabonline/SNAPlabonline/tasks/media/json/testtask.json
{
	"instructions": ["Wear Headphones", "Do Task"],
	"feedback": true,
	"serveraudio": true,
	"trials":[
		{
		"prompt": "Select one of the three options",
		"choices": ["FIRST", "SECOND", "THIRD"],
		"stimulus": "aud.wav",
		"answer": 1
		},
		{
		"prompt": "Select one of the four options",
		"choices": ["FIRST", "SECOND", "THIRD", "FOURTH"],
		"stimulus": "aud.wav",
		"answer": 2
		},
		{
		"prompt": "Select one of the six options",
		"choices": ["FIRST", "SECOND", "THIRD", "FOURTH",
			"FIFTH", "SIXTH"],
		"stimulus": "aud.wav",
		"answer": 3
		}
	]
}
